"""Build local pseudo-label sets from the original F1 strategy dataset.

The primary label set matches competition rows to the original data on the
same non-driver key used by the v4/v7 feature engineering. It is not a full
local leaderboard, but it gives a fast, repeatable proxy for the portion of
test that can be recovered from the public original dataset.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "local_labels"

V4_KEY = [
    "Race",
    "Year",
    "LapNumber",
    "Stint",
    "TyreLife",
    "Position",
    "Compound",
    "PitStop",
]


def unique_orig_labels(orig: pd.DataFrame, keys: list[str]) -> pd.DataFrame:
    grouped = (
        orig[keys + ["PitNextLap"]]
        .groupby(keys, dropna=False)["PitNextLap"]
        .agg(["size", "nunique", "mean"])
        .reset_index()
    )
    unique = grouped[grouped["nunique"] == 1].copy()
    unique["y"] = unique["mean"].round().astype("int8")
    return unique[keys + ["y", "size"]]


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)

    train = pd.read_csv(ROOT / "data/train.csv")
    test = pd.read_csv(ROOT / "data/test.csv")
    orig = pd.read_csv(ROOT / "data/orig/f1_strategy_dataset_v4.csv")

    labels = unique_orig_labels(orig, V4_KEY)

    train_scored = train[["id", "PitNextLap"] + V4_KEY].merge(labels, on=V4_KEY, how="left")
    train_scored = train_scored[train_scored["y"].notna()].copy()
    train_scored["y"] = train_scored["y"].astype("int8")
    train_scored["PitNextLap"] = train_scored["PitNextLap"].astype("int8")
    train_scored["agree"] = (train_scored["PitNextLap"] == train_scored["y"]).astype("int8")

    test_scored = test[["id"] + V4_KEY].merge(labels, on=V4_KEY, how="left")
    test_scored = test_scored[test_scored["y"].notna()].copy()
    test_scored["y"] = test_scored["y"].astype("int8")

    train_path = OUT_DIR / "train_v4_key.csv"
    test_path = OUT_DIR / "test_v4_key.csv"
    meta_path = OUT_DIR / "README.md"

    train_scored[["id", "PitNextLap", "y", "agree", "size"]].to_csv(train_path, index=False)
    test_scored[["id", "y", "size"]].to_csv(test_path, index=False)

    coverage_train = len(train_scored) / len(train)
    coverage_test = len(test_scored) / len(test)
    agreement = train_scored["agree"].mean()

    meta_path.write_text(
        "\n".join(
            [
                "# Local Pseudo Labels",
                "",
                "Generated by `src/make_local_labels.py`.",
                "",
                "These labels come from exact matches to `data/orig/f1_strategy_dataset_v4.csv`",
                "using the v4/v7 key:",
                "",
                "`Race, Year, LapNumber, Stint, TyreLife, Position, Compound, PitStop`",
                "",
                f"- Train coverage: {len(train_scored)} / {len(train)} ({coverage_train:.2%})",
                f"- Train agreement with true target: {agreement:.6f}",
                f"- Test coverage: {len(test_scored)} / {len(test)} ({coverage_test:.2%})",
                f"- Test pseudo-label positive rate: {test_scored['y'].mean():.6f}",
                "",
                "Use this as a fast proxy score, not as the whole competition metric.",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"wrote {train_path.relative_to(ROOT)} ({len(train_scored)} rows)")
    print(f"wrote {test_path.relative_to(ROOT)} ({len(test_scored)} rows)")
    print(f"train coverage: {coverage_train:.2%}")
    print(f"train agreement: {agreement:.6f}")
    print(f"test coverage: {coverage_test:.2%}")
    print(f"test pseudo-label positive rate: {test_scored['y'].mean():.6f}")


if __name__ == "__main__":
    main()
